server:
  port: 18080

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.2:3306/spring-security?useUnicode=true&characterEncoding=utf8
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  messages:
    basename: static/i18n/messages
  mail:
    host: smtp.163.com
    port: 465
    protocol: smtps
    username: USERNAME
    password: PASSWORD
    properties:
      mail:
        transport:
          protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 8000

support:
  email: hfuucmms@163.com


logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy:
              DEBUG